version: 3
locations:
  - name: r1b1
    rack:
      name: rack-1
    board:
      name: board-1
devices:
  - name: temperature
    metadata:
      model: temp2010
    instances:
      - info: Temperature Device 1
        location: r1b1
        data:
          id: 1
      - info: Temperature Device 2
        location: r1b1
        data:
          id: 2
      - info: Temperature Device 3
        location: r1b1
        data:
          id: 3
