version: 3
debug: true
network:
  type: tcp
  address: localhost:5001
settings:
  read:
    interval: 5s
  write:
    interval: 5s
  transaction:
    ttl: 8m
health:
  # disable health file for examples
  healthFile: ""