version: 3
debug: true
network:
  type: unix
  address: example-plugin.sock
settings:
  read:
    interval: 5s
    queueSize: 150
  write:
    interval: 5s
    queueSize: 150
  transaction:
    ttl: 8m
health:
  # disable health file for examples
  healthFile: ""