version: 3
devices:
  - type: led
    handler: example.led
    metadata:
      model: sample-led
    tags:
      - foobar/xyz:led
    instances:
      - info: LED 1
        tags:
          - zone:1
        data:
          id: 1
      - info: LED 2
        tags:
          - zone:2
