version: 1.0
locations:
  - name: unknown
    rack:
      name: unknown
    board:
      name: unknown
devices:
  - name: example.led
    metadata:
      author: vaporio
    outputs:
      - type: simple.led
    instances:
      - info: Chamber LED 1
        location: unknown
        data:
          id: 5
      - info: Chamber LED 2
        location: unknown
        data:
          id: 6
