version: 3
devices:
  - type: temperature
    handler: example.temperature
    metadata:
      model: sample-temperature
    tags:
      - foobar/xyz:temp
    instances:
      - info: Temperature 1
        tags:
          - zone:1
        data:
          id: 1
      - info: Temperature 2
        tags:
          - zone:2
        data:
          id: 2
      - info: Temperature 3
        tags:
          - zone:3
        data:
          id: 3
