version: 3
devices:
  - type: temperature
    handler: example.temperature
    context:
      author: vaporio
    instances:
      - info: CEC Temperature 1
        data:
          id: 1
      - info: CEC Temperature 2
        data:
          id: 2
      - info: CEC Temperature 3
        data:
          id: 3
