version: 1.0
prototypes:
  - type: temperature
    model: temp2010
    manufacturer: vaporio
    protocol: emulator
    output:
      - type: temperature
        data_type: float
        unit:
          name: celsius
          symbol: C
        precision: 2
        range:
          min: 0
          max: 100
