version: 3
devices:
  - type: temperature
    handler: temperature
    context:
      model: temp2010
    instances:
      - info: Temperature 1
        data:
          id: 1
      - info: Temperature 2
        data:
          id: 2
      - info: Temperature 3
        data:
          id: 3
