version: 3
devices:
  - type: airflow
    handler: airflow
    metadata:
      model: air8884
    instances:
      - info: Airflow Device 1
        data:
          id: 1
      - info: Airflow Device 2
        data:
          id: 2
      - info: Airflow Device 3
        data:
          id: 3
