version: 3
devices:
  - type: voltage
    handler: voltage
    context:
      model: volt1103
    instances:
      - info: Voltage Device 1
        data:
          id: 1
      - info: Voltage Device 2
        data:
          id: 2
      - info: Voltage Device 3
        data:
          id: 3
